parameters:
#    back_deal.example.class: Back\DealBundle\Example

services:
#    back_deal.example:
#        class: %back_deal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
