parameters:
#    back_contract.example.class: Back\ContractBundle\Example

services:
#    back_contract.example:
#        class: %back_contract.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
