#entreprise
back_entreprise:
    path:     /
    defaults: { _controller: BackDashBundle:Entreprise:index }

add_entreprise_manager:
    path:     /add
    defaults: { _controller: BackDashBundle:Entreprise:add }
update_entreprise_manager:
    path:     /update/{id}
    defaults: { _controller: BackDashBundle:Entreprise:edit}
    requirements:
        id: \d+
delete_entreprise_manager:
    path:     /delete/{id}
    defaults: { _controller: BackDashBundle:Entreprise:delete}
    requirements:
        id: \d+
