<?php

namespace Proxies\__CG__\Back\DashBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Sms extends \Back\DashBundle\Entity\Sms implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Back\\DashBundle\\Entity\\Sms' . "\0" . 'id', '' . "\0" . 'Back\\DashBundle\\Entity\\Sms' . "\0" . 'title', '' . "\0" . 'Back\\DashBundle\\Entity\\Sms' . "\0" . 'body', '' . "\0" . 'Back\\DashBundle\\Entity\\Sms' . "\0" . 'send', '' . "\0" . 'Back\\DashBundle\\Entity\\Sms' . "\0" . 'total', '' . "\0" . 'Back\\DashBundle\\Entity\\Sms' . "\0" . 'dcr', '' . "\0" . 'Back\\DashBundle\\Entity\\Sms' . "\0" . 'smstmp');
        }

        return array('__isInitialized__', '' . "\0" . 'Back\\DashBundle\\Entity\\Sms' . "\0" . 'id', '' . "\0" . 'Back\\DashBundle\\Entity\\Sms' . "\0" . 'title', '' . "\0" . 'Back\\DashBundle\\Entity\\Sms' . "\0" . 'body', '' . "\0" . 'Back\\DashBundle\\Entity\\Sms' . "\0" . 'send', '' . "\0" . 'Back\\DashBundle\\Entity\\Sms' . "\0" . 'total', '' . "\0" . 'Back\\DashBundle\\Entity\\Sms' . "\0" . 'dcr', '' . "\0" . 'Back\\DashBundle\\Entity\\Sms' . "\0" . 'smstmp');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Sms $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setBody($body)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBody', array($body));

        return parent::setBody($body);
    }

    /**
     * {@inheritDoc}
     */
    public function getBody()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBody', array());

        return parent::getBody();
    }

    /**
     * {@inheritDoc}
     */
    public function setSend($send)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSend', array($send));

        return parent::setSend($send);
    }

    /**
     * {@inheritDoc}
     */
    public function getSend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSend', array());

        return parent::getSend();
    }

    /**
     * {@inheritDoc}
     */
    public function setDcr($dcr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDcr', array($dcr));

        return parent::setDcr($dcr);
    }

    /**
     * {@inheritDoc}
     */
    public function getDcr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDcr', array());

        return parent::getDcr();
    }

    /**
     * {@inheritDoc}
     */
    public function addSmstmp(\Back\DashBundle\Entity\Smstmp $smstmp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSmstmp', array($smstmp));

        return parent::addSmstmp($smstmp);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSmstmp(\Back\DashBundle\Entity\Smstmp $smstmp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSmstmp', array($smstmp));

        return parent::removeSmstmp($smstmp);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmstmp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmstmp', array());

        return parent::getSmstmp();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

}
