<?php

namespace Proxies\__CG__\Main\FrontBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class GpgLog extends \Main\FrontBundle\Entity\GpgLog implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Main\\FrontBundle\\Entity\\GpgLog' . "\0" . 'id', '' . "\0" . 'Main\\FrontBundle\\Entity\\GpgLog' . "\0" . 'datelog', '' . "\0" . 'Main\\FrontBundle\\Entity\\GpgLog' . "\0" . 'data', '' . "\0" . 'Main\\FrontBundle\\Entity\\GpgLog' . "\0" . 'idCommande', '' . "\0" . 'Main\\FrontBundle\\Entity\\GpgLog' . "\0" . 'etatPayement', '' . "\0" . 'Main\\FrontBundle\\Entity\\GpgLog' . "\0" . 'ip');
        }

        return array('__isInitialized__', '' . "\0" . 'Main\\FrontBundle\\Entity\\GpgLog' . "\0" . 'id', '' . "\0" . 'Main\\FrontBundle\\Entity\\GpgLog' . "\0" . 'datelog', '' . "\0" . 'Main\\FrontBundle\\Entity\\GpgLog' . "\0" . 'data', '' . "\0" . 'Main\\FrontBundle\\Entity\\GpgLog' . "\0" . 'idCommande', '' . "\0" . 'Main\\FrontBundle\\Entity\\GpgLog' . "\0" . 'etatPayement', '' . "\0" . 'Main\\FrontBundle\\Entity\\GpgLog' . "\0" . 'ip');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (GpgLog $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatelog($datelog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatelog', array($datelog));

        return parent::setDatelog($datelog);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatelog()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatelog', array());

        return parent::getDatelog();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCommande($idCommande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCommande', array($idCommande));

        return parent::setIdCommande($idCommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCommande', array());

        return parent::getIdCommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatPayement($etatPayement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatPayement', array($etatPayement));

        return parent::setEtatPayement($etatPayement);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatPayement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatPayement', array());

        return parent::getEtatPayement();
    }

    /**
     * {@inheritDoc}
     */
    public function setIp($ip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIp', array($ip));

        return parent::setIp($ip);
    }

    /**
     * {@inheritDoc}
     */
    public function getIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIp', array());

        return parent::getIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data));

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', array());

        return parent::getData();
    }

}
