<?php

namespace Proxies\__CG__\Back\CommandeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Coupon extends \Back\CommandeBundle\Entity\Coupon implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'id', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'price', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'vendu', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'recu', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'client', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'dcr', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'code', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'aramexid', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'aramexpdf', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'command', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'invoice', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'booking');
        }

        return array('__isInitialized__', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'id', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'price', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'vendu', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'recu', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'client', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'dcr', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'code', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'aramexid', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'aramexpdf', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'command', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'invoice', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Coupon' . "\0" . 'booking');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Coupon $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setVendu($vendu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVendu', array($vendu));

        return parent::setVendu($vendu);
    }

    /**
     * {@inheritDoc}
     */
    public function getVendu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVendu', array());

        return parent::getVendu();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecu($recu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecu', array($recu));

        return parent::setRecu($recu);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecu', array());

        return parent::getRecu();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient($client)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', array($client));

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', array());

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setDcr($dcr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDcr', array($dcr));

        return parent::setDcr($dcr);
    }

    /**
     * {@inheritDoc}
     */
    public function getDcr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDcr', array());

        return parent::getDcr();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', array($code));

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', array());

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommand(\Back\CommandeBundle\Entity\Command $command = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommand', array($command));

        return parent::setCommand($command);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommand', array());

        return parent::getCommand();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoice(\Back\PartnerBundle\Entity\Invoice $invoice = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoice', array($invoice));

        return parent::setInvoice($invoice);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoice', array());

        return parent::getInvoice();
    }

    /**
     * {@inheritDoc}
     */
    public function addBooking(\Main\BookingBundle\Entity\Booking $booking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBooking', array($booking));

        return parent::addBooking($booking);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBooking(\Main\BookingBundle\Entity\Booking $booking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBooking', array($booking));

        return parent::removeBooking($booking);
    }

    /**
     * {@inheritDoc}
     */
    public function getBooking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBooking', array());

        return parent::getBooking();
    }

    /**
     * {@inheritDoc}
     */
    public function setAramexid($aramexid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAramexid', array($aramexid));

        return parent::setAramexid($aramexid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAramexid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAramexid', array());

        return parent::getAramexid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAramexpdf($aramexpdf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAramexpdf', array($aramexpdf));

        return parent::setAramexpdf($aramexpdf);
    }

    /**
     * {@inheritDoc}
     */
    public function getAramexpdf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAramexpdf', array());

        return parent::getAramexpdf();
    }

}
