<?php

namespace Proxies\__CG__\User\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \User\UserBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'name', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'bank', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'agency', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'rib', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'address', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'phone', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'webSite', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'fbpage', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'datenaisse', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'cin', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'datecin', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'phoneurg', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'adresseurg', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'tva', 'contactpartner', 'protocol', 'sellingpoint', 'region', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'command', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'caisse', 'category', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'operation', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'dmj', 'profilePictureFile', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'tempProfilePicturePath', 'profilePicturePath', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'localite', 'username', 'usernameCanonical', 'email', 'emailCanonical', 'enabled', 'salt', 'password', 'plainPassword', 'lastLogin', 'confirmationToken', 'passwordRequestedAt', 'groups', 'locked', 'expired', 'expiresAt', 'roles', 'credentialsExpired', 'credentialsExpireAt');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'name', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'bank', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'agency', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'rib', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'address', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'phone', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'webSite', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'fbpage', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'datenaisse', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'cin', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'datecin', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'phoneurg', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'adresseurg', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'tva', 'contactpartner', 'protocol', 'sellingpoint', 'region', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'command', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'caisse', 'category', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'operation', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'dmj', 'profilePictureFile', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'tempProfilePicturePath', 'profilePicturePath', '' . "\0" . 'User\\UserBundle\\Entity\\User' . "\0" . 'localite', 'username', 'usernameCanonical', 'email', 'emailCanonical', 'enabled', 'salt', 'password', 'plainPassword', 'lastLogin', 'confirmationToken', 'passwordRequestedAt', 'groups', 'locked', 'expired', 'expiresAt', 'roles', 'credentialsExpired', 'credentialsExpireAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setProfilePictureFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfilePictureFile', array($file));

        return parent::setProfilePictureFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfilePictureFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfilePictureFile', array());

        return parent::getProfilePictureFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfilePicturePath($profilePicturePath)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfilePicturePath', array($profilePicturePath));

        return parent::setProfilePicturePath($profilePicturePath);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfilePicturePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfilePicturePath', array());

        return parent::getProfilePicturePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfilePictureAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfilePictureAbsolutePath', array());

        return parent::getProfilePictureAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebProfilePicturePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebProfilePicturePath', array());

        return parent::getWebProfilePicturePath();
    }

    /**
     * {@inheritDoc}
     */
    public function preUploadProfilePicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUploadProfilePicture', array());

        return parent::preUploadProfilePicture();
    }

    /**
     * {@inheritDoc}
     */
    public function generateRandomProfilePictureFilename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateRandomProfilePictureFilename', array());

        return parent::generateRandomProfilePictureFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function uploadProfilePicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'uploadProfilePicture', array());

        return parent::uploadProfilePicture();
    }

    /**
     * {@inheritDoc}
     */
    public function removeProfilePictureFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProfilePictureFile', array());

        return parent::removeProfilePictureFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgency($agency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgency', array($agency));

        return parent::setAgency($agency);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgency', array());

        return parent::getAgency();
    }

    /**
     * {@inheritDoc}
     */
    public function setRib($rib)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRib', array($rib));

        return parent::setRib($rib);
    }

    /**
     * {@inheritDoc}
     */
    public function getRib()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRib', array());

        return parent::getRib();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebSite($webSite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebSite', array($webSite));

        return parent::setWebSite($webSite);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebSite', array());

        return parent::getWebSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setFbpage($fbpage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFbpage', array($fbpage));

        return parent::setFbpage($fbpage);
    }

    /**
     * {@inheritDoc}
     */
    public function getFbpage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFbpage', array());

        return parent::getFbpage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatenaisse($datenaisse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatenaisse', array($datenaisse));

        return parent::setDatenaisse($datenaisse);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatenaisse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatenaisse', array());

        return parent::getDatenaisse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCin($cin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', array($cin));

        return parent::setCin($cin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', array());

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecin($datecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecin', array($datecin));

        return parent::setDatecin($datecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecin', array());

        return parent::getDatecin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneurg($phoneurg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneurg', array($phoneurg));

        return parent::setPhoneurg($phoneurg);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneurg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneurg', array());

        return parent::getPhoneurg();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseurg($adresseurg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseurg', array($adresseurg));

        return parent::setAdresseurg($adresseurg);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseurg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseurg', array());

        return parent::getAdresseurg();
    }

    /**
     * {@inheritDoc}
     */
    public function setTva($tva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTva', array($tva));

        return parent::setTva($tva);
    }

    /**
     * {@inheritDoc}
     */
    public function getTva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTva', array());

        return parent::getTva();
    }

    /**
     * {@inheritDoc}
     */
    public function setDmj($dmj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDmj', array($dmj));

        return parent::setDmj($dmj);
    }

    /**
     * {@inheritDoc}
     */
    public function getDmj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDmj', array());

        return parent::getDmj();
    }

    /**
     * {@inheritDoc}
     */
    public function setBank(\Back\CommandeBundle\Entity\Bank $bank = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBank', array($bank));

        return parent::setBank($bank);
    }

    /**
     * {@inheritDoc}
     */
    public function getBank()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBank', array());

        return parent::getBank();
    }

    /**
     * {@inheritDoc}
     */
    public function addContactpartner(\Back\PartnerBundle\Entity\ContactPartner $contactpartner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContactpartner', array($contactpartner));

        return parent::addContactpartner($contactpartner);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContactpartner(\Back\PartnerBundle\Entity\ContactPartner $contactpartner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContactpartner', array($contactpartner));

        return parent::removeContactpartner($contactpartner);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactpartner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactpartner', array());

        return parent::getContactpartner();
    }

    /**
     * {@inheritDoc}
     */
    public function addProtocol(\Back\ContractBundle\Entity\Protocol $protocol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProtocol', array($protocol));

        return parent::addProtocol($protocol);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProtocol(\Back\ContractBundle\Entity\Protocol $protocol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProtocol', array($protocol));

        return parent::removeProtocol($protocol);
    }

    /**
     * {@inheritDoc}
     */
    public function getProtocol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProtocol', array());

        return parent::getProtocol();
    }

    /**
     * {@inheritDoc}
     */
    public function addSellingpoint(\Back\PartnerBundle\Entity\SellingPoint $sellingpoint)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSellingpoint', array($sellingpoint));

        return parent::addSellingpoint($sellingpoint);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSellingpoint(\Back\PartnerBundle\Entity\SellingPoint $sellingpoint)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSellingpoint', array($sellingpoint));

        return parent::removeSellingpoint($sellingpoint);
    }

    /**
     * {@inheritDoc}
     */
    public function getSellingpoint()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSellingpoint', array());

        return parent::getSellingpoint();
    }

    /**
     * {@inheritDoc}
     */
    public function addRegion(\Back\PlanningBundle\Entity\Region $region)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRegion', array($region));

        return parent::addRegion($region);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRegion(\Back\PlanningBundle\Entity\Region $region)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRegion', array($region));

        return parent::removeRegion($region);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegion', array());

        return parent::getRegion();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommand(\Back\CommandeBundle\Entity\Command $command)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommand', array($command));

        return parent::addCommand($command);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommand(\Back\CommandeBundle\Entity\Command $command)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommand', array($command));

        return parent::removeCommand($command);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommand', array());

        return parent::getCommand();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaisse(\Back\CommandeBundle\Entity\Caisse $caisse = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaisse', array($caisse));

        return parent::setCaisse($caisse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaisse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaisse', array());

        return parent::getCaisse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\Back\PlanningBundle\Entity\Category $category = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function addDeal(\Back\DealBundle\Entity\Deal $deal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDeal', array($deal));

        return parent::addDeal($deal);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDeal(\Back\DealBundle\Entity\Deal $deal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDeal', array($deal));

        return parent::removeDeal($deal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeal', array());

        return parent::getDeal();
    }

    /**
     * {@inheritDoc}
     */
    public function addOperation(\Back\CommandeBundle\Entity\Operation $operation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOperation', array($operation));

        return parent::addOperation($operation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOperation(\Back\CommandeBundle\Entity\Operation $operation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOperation', array($operation));

        return parent::removeOperation($operation);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperation', array());

        return parent::getOperation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalite(\Back\CommandeBundle\Entity\Localite $localite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalite', array($localite));

        return parent::setLocalite($localite);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalite', array());

        return parent::getLocalite();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', array($role));

        return parent::addRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', array($serialized));

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsernameCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsernameCanonical', array());

        return parent::getUsernameCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailCanonical', array());

        return parent::getEmailCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainPassword', array());

        return parent::getPlainPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLogin', array());

        return parent::getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationToken', array());

        return parent::getConfirmationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function hasRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRole', array($role));

        return parent::hasRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', array());

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', array());

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', array());

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsExpired', array());

        return parent::isCredentialsExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', array());

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function isExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExpired', array());

        return parent::isExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLocked', array());

        return parent::isLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isSuperAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSuperAdmin', array());

        return parent::isSuperAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', array($role));

        return parent::removeRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsernameCanonical($usernameCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsernameCanonical', array($usernameCanonical));

        return parent::setUsernameCanonical($usernameCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpireAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpireAt', array($date));

        return parent::setCredentialsExpireAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpired($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpired', array($boolean));

        return parent::setCredentialsExpired($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailCanonical($emailCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailCanonical', array($emailCanonical));

        return parent::setEmailCanonical($emailCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', array($boolean));

        return parent::setEnabled($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpired($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpired', array($boolean));

        return parent::setExpired($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiresAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiresAt', array($date));

        return parent::setExpiresAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperAdmin($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperAdmin', array($boolean));

        return parent::setSuperAdmin($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainPassword', array($password));

        return parent::setPlainPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLogin(\DateTime $time = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLogin', array($time));

        return parent::setLastLogin($time);
    }

    /**
     * {@inheritDoc}
     */
    public function setLocked($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocked', array($boolean));

        return parent::setLocked($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationToken($confirmationToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationToken', array($confirmationToken));

        return parent::setConfirmationToken($confirmationToken);
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordRequestedAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordRequestedAt', array($date));

        return parent::setPasswordRequestedAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordRequestedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordRequestedAt', array());

        return parent::getPasswordRequestedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isPasswordRequestNonExpired($ttl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPasswordRequestNonExpired', array($ttl));

        return parent::isPasswordRequestNonExpired($ttl);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', array($roles));

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroups', array());

        return parent::getGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupNames', array());

        return parent::getGroupNames();
    }

    /**
     * {@inheritDoc}
     */
    public function hasGroup($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasGroup', array($name));

        return parent::hasGroup($name);
    }

    /**
     * {@inheritDoc}
     */
    public function addGroup(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGroup', array($group));

        return parent::addGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGroup(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGroup', array($group));

        return parent::removeGroup($group);
    }

}
