<?php

namespace Proxies\__CG__\Back\PartnerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Schedule extends \Back\PartnerBundle\Entity\Schedule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Back\\PartnerBundle\\Entity\\Schedule' . "\0" . 'id', '' . "\0" . 'Back\\PartnerBundle\\Entity\\Schedule' . "\0" . 'day', '' . "\0" . 'Back\\PartnerBundle\\Entity\\Schedule' . "\0" . 'openTimeMorning', '' . "\0" . 'Back\\PartnerBundle\\Entity\\Schedule' . "\0" . 'closeTimeMorning', '' . "\0" . 'Back\\PartnerBundle\\Entity\\Schedule' . "\0" . 'openTimeAfternoon', '' . "\0" . 'Back\\PartnerBundle\\Entity\\Schedule' . "\0" . 'closeTimeAfternoon', '' . "\0" . 'Back\\PartnerBundle\\Entity\\Schedule' . "\0" . 'sellingpoint');
        }

        return array('__isInitialized__', '' . "\0" . 'Back\\PartnerBundle\\Entity\\Schedule' . "\0" . 'id', '' . "\0" . 'Back\\PartnerBundle\\Entity\\Schedule' . "\0" . 'day', '' . "\0" . 'Back\\PartnerBundle\\Entity\\Schedule' . "\0" . 'openTimeMorning', '' . "\0" . 'Back\\PartnerBundle\\Entity\\Schedule' . "\0" . 'closeTimeMorning', '' . "\0" . 'Back\\PartnerBundle\\Entity\\Schedule' . "\0" . 'openTimeAfternoon', '' . "\0" . 'Back\\PartnerBundle\\Entity\\Schedule' . "\0" . 'closeTimeAfternoon', '' . "\0" . 'Back\\PartnerBundle\\Entity\\Schedule' . "\0" . 'sellingpoint');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Schedule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDay($day)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDay', array($day));

        return parent::setDay($day);
    }

    /**
     * {@inheritDoc}
     */
    public function getDay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDay', array());

        return parent::getDay();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpenTimeMorning($openTimeMorning)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpenTimeMorning', array($openTimeMorning));

        return parent::setOpenTimeMorning($openTimeMorning);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpenTimeMorning()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpenTimeMorning', array());

        return parent::getOpenTimeMorning();
    }

    /**
     * {@inheritDoc}
     */
    public function setCloseTimeMorning($closeTimeMorning)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCloseTimeMorning', array($closeTimeMorning));

        return parent::setCloseTimeMorning($closeTimeMorning);
    }

    /**
     * {@inheritDoc}
     */
    public function getCloseTimeMorning()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCloseTimeMorning', array());

        return parent::getCloseTimeMorning();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpenTimeAfternoon($openTimeAfternoon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpenTimeAfternoon', array($openTimeAfternoon));

        return parent::setOpenTimeAfternoon($openTimeAfternoon);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpenTimeAfternoon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpenTimeAfternoon', array());

        return parent::getOpenTimeAfternoon();
    }

    /**
     * {@inheritDoc}
     */
    public function setCloseTimeAfternoon($closeTimeAfternoon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCloseTimeAfternoon', array($closeTimeAfternoon));

        return parent::setCloseTimeAfternoon($closeTimeAfternoon);
    }

    /**
     * {@inheritDoc}
     */
    public function getCloseTimeAfternoon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCloseTimeAfternoon', array());

        return parent::getCloseTimeAfternoon();
    }

    /**
     * {@inheritDoc}
     */
    public function setSellingpoint(\Back\PartnerBundle\Entity\SellingPoint $sellingpoint = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSellingpoint', array($sellingpoint));

        return parent::setSellingpoint($sellingpoint);
    }

    /**
     * {@inheritDoc}
     */
    public function getSellingpoint()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSellingpoint', array());

        return parent::getSellingpoint();
    }

}
