<?php

namespace Proxies\__CG__\Back\CommandeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \Back\CommandeBundle\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'username', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'password', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'salt', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'roles', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'title', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'name', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'fname', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'sex', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'datebirth', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'phone', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'email', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'pwd', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'fbid', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'cin', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'dcr', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'stat', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'bigFid', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'exid', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'adresses', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'command', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'bigfidhistorique', 'lastLogin', 'confirmationToken');
        }

        return array('__isInitialized__', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'username', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'password', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'salt', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'roles', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'title', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'name', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'fname', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'sex', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'datebirth', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'phone', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'email', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'pwd', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'fbid', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'cin', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'dcr', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'stat', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'bigFid', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'exid', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'adresses', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'command', '' . "\0" . 'Back\\CommandeBundle\\Entity\\Client' . "\0" . 'bigfidhistorique', 'lastLogin', 'confirmationToken');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameFname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameFname', array());

        return parent::getNameFname();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', array());

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', array());

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', array());

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', array());

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles($roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', array($roles));

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFname($fname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFname', array($fname));

        return parent::setFname($fname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFname', array());

        return parent::getFname();
    }

    /**
     * {@inheritDoc}
     */
    public function setSex($sex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSex', array($sex));

        return parent::setSex($sex);
    }

    /**
     * {@inheritDoc}
     */
    public function getSex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSex', array());

        return parent::getSex();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatebirth($datebirth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatebirth', array($datebirth));

        return parent::setDatebirth($datebirth);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatebirth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatebirth', array());

        return parent::getDatebirth();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPwd($pwd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPwd', array($pwd));

        return parent::setPwd($pwd);
    }

    /**
     * {@inheritDoc}
     */
    public function getPwd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPwd', array());

        return parent::getPwd();
    }

    /**
     * {@inheritDoc}
     */
    public function setFbid($fbid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFbid', array($fbid));

        return parent::setFbid($fbid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFbid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFbid', array());

        return parent::getFbid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCin($cin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', array($cin));

        return parent::setCin($cin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', array());

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDcr($dcr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDcr', array($dcr));

        return parent::setDcr($dcr);
    }

    /**
     * {@inheritDoc}
     */
    public function getDcr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDcr', array());

        return parent::getDcr();
    }

    /**
     * {@inheritDoc}
     */
    public function setStat($stat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStat', array($stat));

        return parent::setStat($stat);
    }

    /**
     * {@inheritDoc}
     */
    public function getStat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStat', array());

        return parent::getStat();
    }

    /**
     * {@inheritDoc}
     */
    public function setBigFid($bigFid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBigFid', array($bigFid));

        return parent::setBigFid($bigFid);
    }

    /**
     * {@inheritDoc}
     */
    public function getBigFid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBigFid', array());

        return parent::getBigFid();
    }

    /**
     * {@inheritDoc}
     */
    public function setExid($exid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExid', array($exid));

        return parent::setExid($exid);
    }

    /**
     * {@inheritDoc}
     */
    public function getExid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExid', array());

        return parent::getExid();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdress(\Back\CommandeBundle\Entity\Adress $adresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdress', array($adresses));

        return parent::addAdress($adresses);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdress(\Back\CommandeBundle\Entity\Adress $adresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdress', array($adresses));

        return parent::removeAdress($adresses);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresses', array());

        return parent::getAdresses();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommand(\Back\CommandeBundle\Entity\Command $command)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommand', array($command));

        return parent::addCommand($command);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommand(\Back\CommandeBundle\Entity\Command $command)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommand', array($command));

        return parent::removeCommand($command);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommand', array());

        return parent::getCommand();
    }

    /**
     * {@inheritDoc}
     */
    public function addBigfidhistorique(\Back\DashBundle\Entity\BigFidHistorique $bigfidhistorique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBigfidhistorique', array($bigfidhistorique));

        return parent::addBigfidhistorique($bigfidhistorique);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBigfidhistorique(\Back\DashBundle\Entity\BigFidHistorique $bigfidhistorique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBigfidhistorique', array($bigfidhistorique));

        return parent::removeBigfidhistorique($bigfidhistorique);
    }

    /**
     * {@inheritDoc}
     */
    public function getBigfidhistorique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBigfidhistorique', array());

        return parent::getBigfidhistorique();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLogin(\DateTime $time)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLogin', array($time));

        return parent::setLastLogin($time);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLogin', array());

        return parent::getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationToken($confirmationToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationToken', array($confirmationToken));

        return parent::setConfirmationToken($confirmationToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationToken', array());

        return parent::getConfirmationToken();
    }

}
