<?php

namespace Proxies\__CG__\Back\ContractBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Protocol extends \Back\ContractBundle\Entity\Protocol implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Back\\ContractBundle\\Entity\\Protocol' . "\0" . 'id', '' . "\0" . 'Back\\ContractBundle\\Entity\\Protocol' . "\0" . 'datep', '' . "\0" . 'Back\\ContractBundle\\Entity\\Protocol' . "\0" . 'status', 'annexe', 'user', 'entreprise', 'commercial');
        }

        return array('__isInitialized__', '' . "\0" . 'Back\\ContractBundle\\Entity\\Protocol' . "\0" . 'id', '' . "\0" . 'Back\\ContractBundle\\Entity\\Protocol' . "\0" . 'datep', '' . "\0" . 'Back\\ContractBundle\\Entity\\Protocol' . "\0" . 'status', 'annexe', 'user', 'entreprise', 'commercial');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Protocol $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatep($datep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatep', array($datep));

        return parent::setDatep($datep);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatep', array());

        return parent::getDatep();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function addAnnexe(\Back\ContractBundle\Entity\Annexe $annexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAnnexe', array($annexe));

        return parent::addAnnexe($annexe);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAnnexe(\Back\ContractBundle\Entity\Annexe $annexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAnnexe', array($annexe));

        return parent::removeAnnexe($annexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnexe', array());

        return parent::getAnnexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\User\UserBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommercial(\User\UserBundle\Entity\User $commercial = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommercial', array($commercial));

        return parent::setCommercial($commercial);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommercial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommercial', array());

        return parent::getCommercial();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntreprise(\Back\DashBundle\Entity\Entreprise $entreprise = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntreprise', array($entreprise));

        return parent::setEntreprise($entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntreprise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntreprise', array());

        return parent::getEntreprise();
    }

}
