<?php

namespace Back\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{
    public function getRegionTop($query){
        $query = $this->getEntityManager()
            ->createQuery("select region  from
                            Back\PlanningBundle\Entity\Region as region
                            where region.name Like '%$query%'
                            or region.name Like '%$query'
                            or region.name Like '$query%'
                            or region.name = '$query'
                            order by region.name ASC
                            ");

        return $query->getResult();
    }
}
