<?php

namespace Back\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * requiredInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class requiredInfoRepository extends EntityRepository
{
}
