imports:
    - { resource: "@UserUserBundle/Resources/config/security.yml" }

security:
    #acl:
    #    connection: default
    access_control:
        #- { path: ^/dash, role: ROLE_SUPER_ADMIN }

        #- { path: ^/dash/planning/*, roles: [ROLE_SUPER_ADMIN, PALAINER] }
        #- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/Manager/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, role: ROLE_CLIENT }


    role_hierarchy:
        ROLE_CLIENT: ROLE_CLIENT
        PARTENAIRE: PARTENAIRE
        CAISSIER: CAISSIER
        COMMERCIAL: COMMERCIAL
        REDACTEUR: REDACTEUR
        PALAINER: PALAINER
        CHEFSERVISE: CHEFSERVISE
        SERVICECLIENT: SERVICECLIENT
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            entity: { class: Back\CommandeBundle\Entity\Client, property: username }
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: md5
        Back\CommandeBundle\Entity\Client:
            id: md5salted_encoder
    firewalls:
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false
            main:
                pattern: /dash
                form_login:
                    provider:               fos_userbundle
                    csrf_provider:          form.csrf_provider
                    failure_path:           null
                    default_target_path:    /dash/home
                    remember_me:            true
                    always_use_default_target_path: true
                    login_path:             fos_user_security_login
                    use_forward:            true
                    check_path:             fos_user_security_check
                    use_referer: true
                    always_use_default_target_path: false
                logout:
                    path: fos_user_security_logout
                    target: fos_user_security_login
                    invalidate_session: false
                anonymous:    false
            client:
                pattern:   ^/
                anonymous: true
                #provider:  in_memory
                form_login:
                    login_path: identification
                    check_path: login_check_client
                    provider: in_memory
#                    use_forward: true
                    always_use_default_target_path: false
                    use_referer: true
                    default_target_path: /compte.html
#                    target_path_parameter: _target_path
                remember_me:
                    key:      "%secret%"
                    lifetime: 31536000
                    path:     /
                    domain:   ~
                logout:
                    path:   logout_client
                    target: /connexion.html

