<?php

namespace Back\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdressRepository extends EntityRepository
{
}
