<?php

namespace Back\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CheckcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckcRepository extends EntityRepository
{
}
