<?php

namespace Back\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CouponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponRepository extends EntityRepository
{
public function listCouponParDeal($idDeal)
    {
        $query = $this->getEntityManager()
            ->createQuery("select coupon  from
                            Back\CommandeBundle\Entity\Coupon as coupon ,
                            Back\CommandeBundle\Entity\Command as cmd 
                            where  cmd.id = coupon.command 
                            and coupon.vendu =2
                            and cmd.deal =  '" . $idDeal . "'

                            ");

//echo $query->getSQL();
         return $query->getResult();

    }
}
