<?php

namespace Back\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationRepository extends EntityRepository
{




    public function lastRetrait($caisse)
    {
        $sql = "select ope.dcr as dcr ";
        $from = " from Back\CommandeBundle\Entity\Operation as ope,";
        $where = " where ope.caisse = ". $caisse ." and";
        $where .= " ope.user is not null and ";

        $where = substr($where, 0, -4);
        $from = substr($from, 0, -1);
        $query = $sql . $from . $where." order by dcr DESC";
        $qb = $this->getEntityManager()->createQuery($query);
        $result = $qb->getResult();
if(count($result)>0)
{
    return $result[0]['dcr']->format('d/m/Y H:i:s');

}
        else
            return null;

    }

    public function getCommandeCaissier($curentUser) {



            $qb = $this->getEntityManager()->createQuery(
                'SELECT c   FROM Back\CommandeBundle\Entity\Command as c, Back\CommandeBundle\Entity\Operation as o
            WHERE o.user=:iduser and o.commande=c.id AND c.etat=1
            GROUP BY c.id ORDER by c.dpa DESC '
            )->setParameter('iduser', $curentUser);
            return $qb->getResult();

    }

    public function getCommandeListeCaissier($curentUser){
        $qb = $this->getEntityManager()->createQuery(
            'SELECT c   FROM Back\CommandeBundle\Entity\Command as c, Back\CommandeBundle\Entity\Operation as o
            WHERE o.commande=c.id AND c.etat=1
            GROUP BY c.id ORDER by c.dpa DESC '
        );
        return $qb->getResult();
    }
}
