<?php

namespace Back\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentMethodRepository extends EntityRepository
{
    public function getListMethode(){
        $qb=$this->createQueryBuilder('u')
            ->where('u.act = 1')
            ->andWhere('u.id in (:id)')
            ->setParameter('id', array(1,2));
        return $qb->getQuery()->getResult();
    }
}
