imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ BackCommandeBundle, MainFrontBundle,BackPartnerBundle, BackPlanningBundle, BackDealBundle, BackDashBundle  ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            datetime_functions:
                DATE_FORMAT: Main\BookingBundle\DQL\DateFormatFunction
                DATEDIFF: Back\CommandeBundle\DQL\DateDiff

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
knp_menu:
    twig:  
        template: BackDashBundle:Menu:knp_menu.html.twig
    templating: false 
    default_renderer: twig
#FOS USERBUNDLE CONFIGURATION
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: User\UserBundle\Entity\User
    registration:
        form:
            type: user_userbundle_registration

# Paginnation
 
knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: BackDashBundle:Pagination:sliding.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

white_october_breadcrumbs:
    itemClass:          active

#avanlanche
#avalanche_imagine:
#    formats: ['jpg', 'jpeg', 'png', 'gif']
#    filters:
#            type:    thumbnail
#            options: { size: [240, 105], mode: outbound , quality: 80, format: png}
# liipimage bundle
liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        user_profil:
            quality: 100
            filters:
                thumbnail: { size: [240, 105], mode: inset , format: png }
        sliddetaildeal:
            quality: 100
            filters:
                thumbnail: { size: [650, 300], mode: inset , format: png }

        thumbdetaildeal:
            quality: 100
            filters:
                thumbnail: { size: [141, 141], mode: inset , format: png }
        thumbcommandedeal:
            quality: 100
            filters:
                thumbnail: { size: [125, 80], mode: inset , format: png }
        homedeal:
            quality: 100
            filters:
                upscale: { min: [590, 249] }
                #thumbnail: { size: [590, 304], mode: inset , format: png }
        jcarouselhome:
            quality: 100
            filters:
                upscale: { min: [950, 390] }
        serviceclient:
            quality: 70
            filters:
                thumbnail: { size: [100, 100], mode: inset , format: png }
# plugin twig
services:

    notifListener:
        class: Back\CommandeBundle\Listener\NotifListener
        arguments: [@service_container,@session,@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    request:
        class:        Symfony\Component\HttpFoundation\Request
    back.twig.dash_extension:
        class: Back\DashBundle\Twig\TwigExtension
        arguments: [@doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: twig.extension }

    booking.twig_extension:
            class: Main\BookingBundle\Twig\Extension\BookingExtension
            public: true
            tags:
                - { name: twig.extension }
            arguments:
                        em: "@doctrine.orm.entity_manager"

    caisse.twig_extension:
                class: Back\CommandeBundle\Twig\Extension\CaisseExtension
                public: true
                tags:
                    - { name: twig.extension }
                arguments:
                            em: "@doctrine.orm.entity_manager"
    contact.twig_extension:
                class: Back\PartnerBundle\Twig\Extension\ContactExtension
                public: true
                tags:
                    - { name: twig.extension }
                arguments:
                            em: "@doctrine.orm.entity_manager"
dcs_rating:
    db_driver: orm
    base_path_to_redirect: / # when the permalink is not configured
    max_value: 5 # maximum value for the vote (stars displayed)
    model:
        rating: Back\DealBundle\Entity\Rating
        vote: Back\DealBundle\Entity\Vote
