<?php

namespace Back\DashBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegleRepository extends EntityRepository
{
    public function bigFidInscription($idClient)
    {
        $sql = "select count(reg) as nombre ";
        $from = " from Back\DashBundle\Entity\Regle as reg ,";

        $where = " where reg.starDate < = '" . date('Y-m-d') . "' and";
        $where .= "  reg.endDate  > = '" . date('Y-m-d') . "' and";
        $where .= "  reg.act   = 1 and";
        $where .= "  reg.id   = 1 and";
        $where = substr($where, 0, -4);
        $from = substr($from, 0, -1);
        $query = $sql . $from . $where;
        $qb = $this->getEntityManager()->createQuery($query);
        return $qb->getResult();
    }

    public function activerPartage()
    {
        $sql = "select count(*) as nombre ";
        $from = " from Back\DashBundle\Entity\Regle as reg ,";

        $where = " where reg.starDate < = '" . date('Y-m-d') . "' and";
        $where .= "  reg.endDate  > = '" . date('Y-m-d') . "' and";
        $where .= "  reg.act   = 1 and";
        $where .= "  reg.id   = 2 and";
        $where = substr($where, 0, -4);
        $from = substr($from, 0, -1);
        $query = $sql . $from . $where;
        $qb = $this->getEntityManager()->createQuery($query);
        return $qb->getResult();
    }

    public function activerAchatEnLigne()
    {
        $sql = "select count(*) as nombre ";
        $from = " from Back\DashBundle\Entity\Regle as reg ,";

        $where = " where reg.starDate < = '" . date('Y-m-d') . "' and";
        $where .= "  reg.endDate  > = '" . date('Y-m-d') . "' and";
        $where .= "  reg.act   = 1 and";
        $where .= "  reg.id   = 3 and";
        $where = substr($where, 0, -4);
        $from = substr($from, 0, -1);
        $query = $sql . $from . $where;
        $qb = $this->getEntityManager()->createQuery($query);
        return $qb->getResult();
    }
}
