<?php

namespace Back\DashBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SmstmpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmstmpRepository extends EntityRepository
{
}
