<?php

namespace Back\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository
{
    public function getActivBanner($zone)
    {
        $dt=new \DateTime();
        $qb = $this->createQueryBuilder('r')
            ->where("r.dated <='" . $dt->format("Y-m-d") . "'")
            ->Where("r.datef >= '" . $dt->format("Y-m-d") . "'")
            ->andWhere("r.act=1 " )
            ->andWhere("r.zone= ".$zone )->getQuery()
            ->getResult();

       return $qb;
    }
}
