#categorie
back_reponseRequiredInfo:
    path:     /
    defaults: { _controller: BackPlanningBundle:ResponseRequiredInfo:index }

add_reponseRequiredInfo_manager:
    path:     /add
    defaults: { _controller: BackPlanningBundle:ResponseRequiredInfo:add }
update_reponseRequiredInfo_manager:
    path:     /update/{id}
    defaults: { _controller: BackPlanningBundle:ResponseRequiredInfo:edit}
    requirements:
        id: \d+
delete_reponseRequiredInfo_manager:
    path:     /delete/{id}
    defaults: { _controller: BackPlanningBundle:ResponseRequiredInfo:delete}
    requirements:
        id: \d+
