<?php

namespace Back\DealBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CompagneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompagneRepository extends EntityRepository
{

    public function getComp($page, $nbPerPage)
    {

            $query = $this->createQueryBuilder('a')
                ->orderBy('a.datecreated', 'DESC')
                ->getQuery()
            ;

            $query
                // On définit l'annonce à partir de laquelle commencer la liste
                ->setFirstResult(($page-1) * $nbPerPage)
                // Ainsi que le nombre d'annonce à afficher sur une page
                ->setMaxResults($nbPerPage)
            ;

            // Enfin, on retourne l'objet Paginator correspondant à la requête construite
            // (n'oubliez pas le use correspondant en début de fichier)


        return new Paginator($query, true);
    }










}
