<?php

namespace Back\DealBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DealhistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealhistoryRepository extends EntityRepository
{
    public function findByDate($dated,$datef,$idcategorie,$idregion,$idredact=""){
        $sql="select distinct deal  from
            Back\DealBundle\Entity\Dealhistory as history ,
            Back\DealBundle\Entity\Deal as deal ,
            Back\PlanningBundle\Entity\Planning as plan
            where  deal.planning=plan.id
            and history.deal=deal.id
            and plan.state=3
            and history.dcr >= '".$dated->format('Y-m-d')." 00:00:00'
            and history.dcr <='".$datef->format('Y-m-d')." 23:59:59'";
        if($idredact>0){
            $sql .= " and deal.redacteur=".$idredact;
        }
        if($idcategorie>0){
            $sql .= " and plan.categoryId=".$idcategorie;
        }if($idregion>0){
            $sql .= " and plan.regionId=".$idregion;
        }
        $sql .="   order by history.dcr ASC";
        $query = $this->getEntityManager()
            ->createQuery($sql);
        //echo $query->getSQL();exit;
        return $query->getResult();
    }
}
