parameters:
#    back_partner.example.class: Back\PartnerBundle\Example

services:
#    back_partner.example:
#        class: %back_partner.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
