<?php

namespace Back\ContractBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Back\DashBundle\Common\Tools;
/**
 * ProtocolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocolRepository extends EntityRepository
{
    public function findByFilter($criteria,$orderBy=array()){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $expr = $this->getEntityManager()->getExpressionBuilder();
        $qb->select( 'entity' )
            ->from( $this->getEntityName(), 'entity' );
        //Tools::dump($criteria,true);
        if(isset($criteria['datepd'])){
            $dpaf = Tools::reformatDate($criteria['datepd']);
            $qb->andWhere("entity.datep >= '".$dpaf->format('Y-m-d')."'");
        }
        if(isset($criteria['datepf'])){
            $dpaf = Tools::reformatDate($criteria['datepf']);
            $qb->andWhere("entity.datep <= '".$dpaf->format('Y-m-d')."'");
        }
        if(isset($criteria['status'])){
            $qb->andWhere("entity.status = ".$criteria['status']);
        }
        if(isset($criteria['user'])){
            $qb->andWhere("entity.user = ".$criteria['user']);
        }

        if ( $orderBy ) {

            foreach ( $orderBy as $field => $order ) {

                $qb->addOrderBy( 'entity.' . $field, $order );
            }
        }


       // echo $qb->getQuery()->getSQL();exit;
        return $qb->getQuery()
            ->getResult();
    }
}
